name: Python Addition Check

on: [push, pull_request]

jobs:
  check-math:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Check out your code for Python linting
      - name: Run Flake8
        uses: TrueBrain/setup-python@v5

      # Step 3: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Run the script
      - name: Run addition script
        run: python calc.py
